services:
  cloudflare-tunnel-xui:
    container_name: cloudflare-tunnel-xui
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    # image: cloudflare-tunnel-xui:latest
    restart: unless-stopped
    network_mode: host
    environment:
      HOST: 0.0.0.0
      PORT: 8866
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      no_proxy: ""
      NO_PROXY: ""
    volumes:
      - ./config.json:/app/config.json
      - ./bin:/app/bin
      - ./.cloudflared:/app/.cloudflared